### ISSUE TITLE
Usage from multiple threads

### ISSUE THREAD

**Issue by gauravkumar37** [arangodb/arangodb-java-driver-async#1]
I am planning on moving from driver v3 to async v4.1 and was wondering how to achieve good performance. Since async driver uses VelocyStream which uses binary socket protocol under the hood, it means only 1 thread can read/write from/to ArangoDB at a time. This is what I have also observed. Even if I create as many drivers as I have number of threads, still performance is below par. Infact, with more drivers, deadlock occurs and the application does not respond.
Can you please share some code samples for usage guidelines in a multi-threaded environment?
Thanks,
GK

**Comment by mvollmary** [comment]
Hi, sorry for the late response.
The async driver creates a reading thread under the hood with each instance of `ArangoDBAsync`.  So you can write multiple messages with your main thread without waiting for a response. The read thread reads the server responses and inform the `CompletableFuture`'s from the main thread.

Every API call in the async driver returns you a `CompletableFuture`. If you have not worked with it before check out [https://community.oracle.com/docs/DOC-995305](https://community.oracle.com/docs/DOC-995305).

The key of working with the async driver is not to use the thread blocking `get()` method of `CompletableFuture`. Using `get()` is like working with the sync driver. Instead you can use `whenComplete(BiConsumer)` which is only executed at the time when you get the respone from the server.

    ArangoDBAsync arangoDB = new ArangoDBAsync.Builder().build();
    ArangoCollectionAsync collection = arangoDB.db().collection("myCollection");

    {
      // BAD
      // this will wait for the response and block your thread
      DocumentCreateEntity<BaseDocument> doc = collection.insertDocument(new BaseDocument()).get();
      System.out.println(doc.getKey());
    }
    {
      // GOOD
      // this do not block your thread
      collection.insertDocument(new BaseDocument()).whenComplete((doc, exception) -> {
        System.out.println(doc.getKey());
      });
    }

**Comment by agrothe** [comment]
@mpv1989 can you perhaps add a wiki page explaining the suggested way to use the driver in terms of pooling? I came looking for information about connection pooling and found this thread. I understand the above about CompletableFutures, but should I only have one ArangoDBAsync per application or maintain a pool of them?

**Comment by mvollmary** [comment]
[updated docs](https://github.com/arangodb/arangodb-java-driver-async/blob/master/docs/setup.md#connection-pooling)
