### ISSUE TITLE
README.md outdated

### ISSUE THREAD

**Issue by malte-behrendt** [arangodb/arangodb-java-driver-async#10]
In section "Maven", the readme.md still points to version 4.3.0 instead of 4.3.2. 

As I blindly copied the maven code I ran into the Long value deserialization bug (https://github.com/arangodb/arangodb-java-driver/issues/151) until I noticed 4.3.2 is the current version - which fixes the issue. I guess I won't be the only one to copy the code unchecked, please fix. Thanks!

**Comment by mvollmary** [comment]
Thanks for reporting. README now up-to-date
