### ISSUE TITLE
ArangoSerialization no longer accessible

### ISSUE THREAD

**Issue by falmiski-cr** [arangodb/arangodb-java-driver-async#12]
After updating to the 4.6 async java driver from 4.4, the following code broke

```
   protected ArangoSerialization getSerializer() {
       //ArangoDatabaseAsync instance below
        return arangoDatabaseAsync.util();
    }

```
I have found a less than ideal workaround (below)

    protected ArangoSerialization getSerializer() {
        return ((ArangoDBAsyncImpl) arangoDatabaseAsync.arango()).util();
    }

Can you please expose ArangoSerialization at one of the the interface levels, or explain to me why not?

**Comment by mvollmary** [comment]
@falmiski-cr thanks for reporting. This was forgotten during refactoring. I will add the method again. Sorry

**Comment by falmiski-cr** [comment]
No worries -- thanks for the prompt reply.

**Comment by mvollmary** [comment]
Problem solved with current version
