### ISSUE TITLE
More type options for passing JSON from Jackson

### ISSUE THREAD

**Issue by jbrisbin** [arangodb/arangodb-java-driver-async#9]
I'm trying out ArangoDB in a Dropwizard application and I already have annotations on my POJOs for validation and serialization/deserialization of them using Jackson's `ObjectMapper`. I'd like to have more options around creating a `VPackSlice` for sending to ArangoDB than just a `String`. `byte[]` and or `ByteBuffer` would be better (the latter's useful in situations where you're pooling buffers). Better yet, I'd rather have a `Module` implementation that I could register in Jackson that would let me natively convert my POJOs to `VPackSlice`s by using `mapper.convertValue(pojo, VPackSlice.class)`.

**Comment by mvollmary** [comment]
Hi,

I already started a jackson module for velocypack (look [here](https://github.com/arangodb/jackson-dataformat-velocypack)) but I had no time in the last month to work on that. I hope I find some time at the beginning of the next year, but I can't promise.

**Comment by rashtao** [comment]
You can use [jackson-dataformat-velocypack ](https://github.com/arangodb/jackson-dataformat-velocypack) for this purpose.
